### ISSUE TITLE
Accounts are not loading after cancelling import

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#1012]
**Describe the bug**
When the "Cancel" button is clicked during an import, the transaction list is shown, but transactions to new accounts are shown as transfers.

**To Reproduce**

1. Import transactions to new accounts
2. Click "Cancel"
3. See that the transaction list shows these transactions as transfers. Clicking on them 

**Expected behavior**
The transactions should be displayed with their accounts

**Comment by malfynnction** [comment]
Fixed in #1341
