### ISSUE TITLE
Transaction Import: Sending an empty CSV file leads to blank page

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#1014]
**Describe the bug**
When the CSV to import is empty or leads to an empty response (that happens when it only has one line which is treated as header), the page loads as blank when selecting "Submit"

**To Reproduce**

1. Create an empty `.csv` file
2. Go to the transaction import
3. Try to import the file

**Expected behavior**
A notice that there were no transactions to be imported in the file

**Comment by malfynnction** [comment]
@morremeyer I always see this error message (as expected):
![image](https://github.com/envelope-zero/frontend/assets/24372341/6e1a3ff3-68f2-47f7-b71a-51cbea9e1907)

Could you maybe send me a file that triggers this behavior for you?

**Comment by morremeyer** [comment]
I can't reproduce this anymore. The updates to [you-need-a-parser](https://github.com/envelope-zero/you-need-a-parser) probably fixed it.
