### ISSUE TITLE
Add version information to menu

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#109]
The menu should have a small version information in the bottom left. This can be anything (git commit, empty, string „unknown“) for non-tagged builds, but should be the tagged version for builds from git tags.

Ideally, this shows both the frontend and the backend version.

**Comment by malfynnction** [comment]
I think we should only show the frontend version – most of the time the frontend version implies a certain backend version for compatibility, and anything beyond that is not relevant enough to warrant showing the backend version in the UI imo
