### ISSUE TITLE
Form does not update when transaction is deleted

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#1289]
**Describe the bug**
When deleting a transaction, the transaction form stays open.
There is no indication to the user that the deletion was successful.

**To Reproduce**
1. Delete a transaction with the "Delete" button
2. Observe that nothing happens

**Expected behavior**
The transaction form is closed and the transaction list loaded

**Comment by malfynnction** [comment]
> There is no indication to the user that the deletion was successful.

This is fixed in https://github.com/envelope-zero/frontend/pull/1294

> When deleting a transaction, the transaction form stays open.

I can't reproduce this part 🤔 It should always redirect you back to the page you're coming from. How did you get to the transaction page?

**Comment by morremeyer** [comment]
I ran into this yesterday, but also had some network issues due to an incorrect VPN configuration. With that configuration fixed, I can't reproduce it anymore.
