### ISSUE TITLE
Alternate month picker has poor contrast in dark mode

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#1435]
**Describe the bug**
The month picker for browsers that do not support input type `month` has poor contrast in dark mode.

**To Reproduce**

You need to use a browser that does not support month pickers, e.g. Firefox, to replicate this.

1. Set your frontend to dark mode
2. Go to "Home"
3. Click the calendar symbol in the top bar

**Expected behavior**
Month picker should have enough contrast in dark mode

**Screenshots**
![image](https://github.com/envelope-zero/frontend/assets/7683567/dd44a82e-68b9-40ab-ac53-cfb741d98fe8)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox

**Comment by malfynnction** [comment]
@morremeyer This should be fixed in https://github.com/envelope-zero/frontend/releases/tag/3.2.0, can you please confirm?

**Comment by morremeyer** [comment]
Still looks off 
<img width="270" alt="Screenshot 2024-01-24 at 22 04 08" src="https://github.com/envelope-zero/frontend/assets/7683567/b1627f3d-a8ed-4cfe-8449-d0e44a08aafe">

**Comment by malfynnction** [comment]
@morremeyer Should be fixed (for real) in https://github.com/envelope-zero/frontend/releases/tag/3.3.0. Can you please confirm?

**Comment by morremeyer** [comment]
Yup, works perfectly now.
