### ISSUE TITLE
Improve screen size breakpoints

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#1490]
**Is your feature request related to a problem? Please describe.**
On my phone, in landscape mode, the menu bar is showing, which kind of cramps the dashboard.

![screenshot](https://github.com/envelope-zero/frontend/assets/7683567/3a9cde8b-9017-4852-9421-44469e71bcb6)

**Describe the solution you'd like**
Collapse the menu into a hamburger menu.

**Additional context**
Using a Fairphone 4 with the following display specs: 1080 x 2340 pixels, 409 ppi

**Comment by malfynnction** [comment]
@morremeyer Can you please confirm if this is fixed in https://github.com/envelope-zero/frontend/releases/tag/3.3.0 now?

**Comment by morremeyer** [comment]
Yup, looks good!
