### ISSUE TITLE
`@envelope-zero/ynap-parsers` requires an authentication token

### ISSUE THREAD

**Issue by sigmike** [envelope-zero/frontend#1559]
**Describe the bug**
Running `npm install` raises this error:

> npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@envelope-zero/ynap-parsers/1.17.1/531f91debdff73e12f1de0b535f2ba5481f218b1 - authentication token not provided

**To Reproduce**

1. Remove any npm authentication from your environment, I guess
2. Clone the repository
3. Run `npm install`

**Expected behavior**
`npm install` should succeed without additional authentication.

**Desktop:**

- OS: Linux
- Browser: None
- Version: main branch

**Comment by morremeyer** [comment]
Unfortunately, GitHub does not allow anonymous access to the npm registry, even if it's read only for a public package.

For now, you'll have to perform the second step in https://github.com/envelope-zero/frontend/blob/main/CONTRIBUTING.md#tool--repository-setup for `npm install` to succeed.

We've been thinking about pushing the `ynap-parsers` package to npm also, but that has not been implemented yet.

**Comment by morremeyer** [comment]
@sigmike This will be fixed once #1576 is merged. If you want to give it a try already, check out `chore/parsers-from-npm`.
