### ISSUE TITLE
Integer amount expected on Repeat transaction

### ISSUE THREAD

**Issue by fhreichert** [envelope-zero/frontend#438]
**Describe the bug**
After Repeating a transaction, the Amount field expects an Integer

**To Reproduce**

1. Select a Transaction
2. Click on "Repeat Transaction"
3. Change Amount

**Expected behavior**
Being allowed to enter a non-Integer value

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44102996/195450377-4c8cf3f0-6b60-4adc-a467-4c4a3e920bdc.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser firefox
- Version 105.0.3 (64-Bit)

**Comment by fhreichert** [comment]
Interestingly enough, pressing "Save" saves the decimal amount

**Comment by malfynnction** [comment]
@morremeyer I think the bug you found is related to this, could you please add it here? :)

**Comment by morremeyer** [comment]
Yes, the same thing happens when editing an allocation in the Dashboard: Pressing the checkmark button saves the decimal amount, pressing enter prompts for an integer input

![image](https://user-images.githubusercontent.com/7683567/195539161-e3cd8a46-0985-406c-9630-e56b460734d0.png)
