### ISSUE TITLE
The Day of month is removed from the input field, if month is changed

### ISSUE THREAD

**Issue by fhreichert** [envelope-zero/frontend#439]
**Describe the bug**
The Day of month is removed from the input field, if month is changed.

**To Reproduce**

1. Go to 'Add Transaction'
2. Enter Date of month in 'Date' field e.g. 08
3. Enter Month e.g. 09

**Expected behavior**
The Day of month being unchanged when the month is changed

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44102996/195450838-8eea6c61-6e07-4fbe-bb47-3a3f5f8e0749.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser firefox
- Version 105.0.3 (64-Bit)

**Comment by malfynnction** [comment]
@fhreichert That's weird, I can't reproduce this one. 🤔
Did you enter the date by keyboard or select it from the date picker?
And what version of the frontend was this? The date should be set to the current date by default, so the year shouldn't be "JJJJ" either. Was that also reset when you entered the month, or was it never set correctly to begin with?

**Comment by malfynnction** [comment]
Update: The problem seems to be Firefox clearing the input field when you type the number 0. 🙃
