### ISSUE TITLE
Balance 0 is shown positive and negative in dashboard

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#441]
**Describe the bug**
If there is a negative balance and one adds an allocation to balance it out to 0, the balance is shown in red.

**To Reproduce**

1. Create a negative balance in an envelope
2. Go to the dashboard
3. Edit the allocation for that Envelope to make the balance exactly 0

**Expected behavior**
0 should be the same color as positive values or a neutral color.

**Screenshots**
![image](https://user-images.githubusercontent.com/7683567/195543796-1608a657-4718-48bf-835b-abca71a1caba.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox
- Version 105.0.3

**Comment by malfynnction** [comment]
@morremeyer I can't reproduce this one 🤔 Can you please check if this is still happening on 1.0.0?

**Comment by malfynnction** [comment]
@morremeyer This turned out to be a backend bug, right? Could you link the according issue and close this one? :)

**Comment by morremeyer** [comment]
I looked at it in the backend and found that there was a rounding error somewhere. The returned balance for the envelope that showed the red `0.00 €` was `0.000000004` (+- a few zeros). 

I tried reproducing it right now and could not do so. Therefore closing it without linking to a backend issue.
