### ISSUE TITLE
Dashboard: Switching the month during editing of an allocation does not update the amount

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#518]
**Describe the bug**
When the Month is changed via the Dashboard selection while having the allocations edit input field open, the month is switched, but the value in the input field is not updated to the allocation for the envelope for that month.

**To Reproduce**

1. Create an envelope
2. Go to the dashboard and set any sum as the allocation for the current month. Save the allocation.
3. Edit the allocation again, while the input is visible, switch to the next month
4. See that the allocation amount for the last month is still displayed instead of updating

**Expected behavior**
Amount in the input field should be updated to the amount of the allocation for the new month.

**Comment by malfynnction** [comment]
@morremeyer I'm not sure I understand the problem - for me it works exactly how I would expect it to behave. 🤔
![Dec-04-2022 13-14-07](https://user-images.githubusercontent.com/24372341/205489848-f8df835a-8c37-4538-8aac-c65651d85963.gif)

**Comment by morremeyer** [comment]
I cannot reproduce it anymore with 1.6.0. Looks like some other change fixed this, too.

I won't complain about that :D
