### ISSUE TITLE
Enable setting of overspend handling

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#526]
**Is your feature request related to a problem? Please describe.**
The backend now allows to configure overspend handling, see the `MonthConfigs` endpoints. This enables us to implement the configuration of overspend handling on the frontend.

The default for overspend handling on the backend will be to affect the sum available to budget in the following month (`AFFECT_AVAILABLE`).

**Describe the solution you'd like**

When an envelope has overspend in a month, make that sum clickable to show some kind of dialog that allows setting the overspend handling for the envelope for that month. This can be one of two values: “Affect “Available to Budget” next month“ or “Affect envelope balance next month”.

**Comment by malfynnction** [comment]
Will be done in #615

**Comment by malfynnction** [comment]
@morremeyer Do we still want this?

**Comment by morremeyer** [comment]
No, the feature was removed. Thanks for the reminder.
