### ISSUE TITLE
Hide accounts, envelopes and categories 

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#533]
**Is your feature request related to a problem? Please describe.**
If an account, envelope or category is not used anymore, it should be possible to hide them. 

The backend has a `hidden` field for all of these resources.

**Describe the solution you'd like**

* Do not show resources that have the `hidden` attribute set to `true` in lists.
* Add a possibility to explictly show hidden resources 
* Make the hidden attribute configurable in the detail views of a resource

**Comment by malfynnction** [comment]
@morremeyer What about hidden categories that have non-hidden envelopes? Should that be possible and if yes, how should they be displayed in the envelope list?

**Comment by malfynnction** [comment]
TODO: don't suggest archived accounts & envelopes in transaction form dropdowns. When entering their complete name (instead of offering to create a new resource with that name), show it with an archive icon next to its name.
