### ISSUE TITLE
Change allocations *by* a certain amount

### ISSUE THREAD

**Issue by fhreichert** [envelope-zero/frontend#607]
**Is your feature request related to a problem? Please describe.**
Changing allocations requires mental arithmetic or a calulator. E.G. adding 15,26€ to an allocation of 1234,56€ is not easily done.

**Describe the solution you'd like**
Being able to change allocations by a certain amount.

**Describe alternatives you've considered**
Roll20, a virtual tabletop has this feature for tokens and uses a simple input strategy so no additional fields are necessary:

Scenario: Allocation is 1000
Type "300" in the allocation field, allocation will be set to 300
Type "+300", allocation will be  1300
Type "-300", allocation will be  700

This is not perfect, as it makes entering negative Amounts a bit uninuitive, but not impossible.

**Comment by malfynnction** [comment]
@fhreichert I integrated a possible solution to this in https://github.com/envelope-zero/frontend/issues/615 – would love to hear your feedback!
