### ISSUE TITLE
Transfer from internal on-budget to internal off-budget account is shown as transfer in transaction list

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#618]
**Describe the bug**
Any transfer from internal on-budget to internal off-budget account is shown as a transfer in transaction list, not as an outflow

In the screenshot below, checking is an on-budget and savings an off-budget account.

![Screenshot of transaction being treated as transfer](https://user-images.githubusercontent.com/7683567/210986925-e0688308-5580-4af2-a513-a6f9dc47483b.png)

**To Reproduce**

1. Create a budget, an internal on-budget and an internal off-budget account
2. Create a transaction with the on-budget account as source and the off-budget account as destination

**Expected behavior**
* The transaction should be shown as an outflow (- prefix, red text)
* A transaction from an internal off-budget account to an internal on-budget account should be shown as income.

**Comment by malfynnction** [comment]
@morremeyer Then how should transactions external -> off-budget and off-budget -> external be displayed?

**Comment by morremeyer** [comment]
We currently show transfers in blue, outgoing in red and incoming in green.

![image](https://user-images.githubusercontent.com/7683567/211196879-18b1e4ba-68cd-41ab-9cb8-2292277eb986.png)

I'd say that we use the same signs (+, -, ±), but a neutral color, which would probably be black?

**Comment by malfynnction** [comment]
So you're suggesting that for example internal (on-budget) -> internal (off-budget) is shown in red with a -, and external -> internal (off-budget) is shown in black with a +? That doesn't seem very consistent to me. 🤔

**Comment by morremeyer** [comment]
After some more discussion, I changed my opinion. Let's mark everything that does not affect the budget in **blue**.

**Comment by morremeyer** [comment]
Closing this for now since internal -> internal is a transfer as per https://github.com/envelope-zero/backend/issues/565
