### ISSUE TITLE
Spent amounts use wrong sign

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#620]
**Describe the bug**
The spent amount on the Dashboard currently uses a wrong sign. Outgoing is positive, incoming is negative and displayed green.

**Expected behavior**
Spent sum should be:

- negative sign and a neutral color if there's more outgoing than incoming
- not displayed if it is 0
- positive sign and green if there's more incoming than outgoing

**Implementation hints**

This is waiting for https://github.com/envelope-zero/backend/issues/527 to fix the sign on the spent sum.

Once that's implemented, to resolve this issue the colors need to be updated and `signDisplay` needs to be set to `always`.

**Comment by malfynnction** [comment]
Fixed by https://github.com/envelope-zero/frontend/pull/626
