### ISSUE TITLE
Add/Subtract Amount has too much precision

### ISSUE THREAD

**Issue by fhreichert** [envelope-zero/frontend#633]
**Describe the bug**
Add/Subtract Amount has too much precision: On entering some values, unexpected values are autofilled.

**To Reproduce**

1. Have an allocation set to -400
2. Enter Field "Add/Subtract Amount"
3. Enter "36,7"
4. See error: Value canges to "63.69999999999999"

**Expected behavior**

**Screenshots**
<img width="495" alt="grafik" src="https://user-images.githubusercontent.com/44102996/211159273-2d0d0ff0-b241-44f3-9b44-3cdd6e09442d.png">

**Desktop (please complete the following information):**

- OS: MacOS 13.0.1
- Browser Firefox 
- Version 13.0.1

**Additional context**

**Comment by malfynnction** [comment]
@fhreichert 
> 3. Enter "36,7"

You mean 63 and not 36, right? Because otherwise this would be even more problematic :eyes:
