### ISSUE TITLE
Improve visibility of envelope notes

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#768]
**Is your feature request related to a problem? Please describe.**
Currently, it's hard to get to a note for an envelope. I need to select the envelope from the envelope list to view and edit it.

**Describe the solution you'd like**
Envelope notes should be readable and writeable on the dashboard.

**Comment by malfynnction** [comment]
@morremeyer Is the solution to #844 enough for this? Because I would rather have the month config's note available on the dashboard (see #767)  – and I think having both the month config note and the envelope note would be too much and probably just confusing.

**Comment by morremeyer** [comment]
Yes, sounds good.
