### ISSUE TITLE
Add „availableFrom“ to transactions 

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#781]
**Is your feature request related to a problem? Please describe.**
The API has a field `availableFrom` for transactions. That field describes from which date on money in a transaction is available for budgeting.

**Describe the solution you'd like**
Expose the field in the frontend with a date picker. For new transactions, default to the current date.

**Comment by malfynnction** [comment]
How is that different from the date field on a transaction?

**Comment by morremeyer** [comment]
It describes the availability for budgeting purposes, not when it's actually booked on the account. This is needed to ensure that one can't over-budget accidentally.

Picture:

* At the first of the month, you have 100€ available
* Your salary of 500€ gets paid on the 25th

For that salary, the `availableFrom` will now typically be set to the first of the following month by the user.
If they did not do that, the current month would claim to have 600€ available, but most of that (the 500 salary paid on 25th) is only available at the end of the month.

If the user would now the 100€ on groceries on the 5th, they would not have anything available until the 25th, but the budget would claim they have 500€.

This would essentially lead to them spending money they don't have.
