### ISSUE TITLE
Filter and plus icon are sticky in transaction list

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/frontend#920]
**Describe the bug**

<img width="147" alt="image" src="https://github.com/envelope-zero/frontend/assets/7683567/8564daad-125a-4908-b055-5726137378e2">

**To Reproduce**

1. Open a transaction list that is long enough to be scrollable

**Expected behavior**

Filter and plus icon are either:

* Sticky, but with a nice layout and together with the search bar
* not sticky

**Comment by malfynnction** [comment]
This does not seem to be happening anymore. @morremeyer can you confirm?

**Comment by morremeyer** [comment]
I can still reproduce it on 1.22.5
